default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  port: 5432
  database: bobby_hr
  username: postgres
  password: password

production:
  <<: *default
  host: localhost
  port: 5432
  database: bobby_hr
  username: postgres
  password: password

test:
  adapter: sqlite3
  database: storage/db.sqlite3
  pool: 5
  timeout: 5000
